version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kaua/gesttask
        restart: unless-stopped
        # command: "composer install && php artisan migrate"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - gesttaskapp

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - gesttaskapp

    mysql:
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        restart: always
        ports:
            - "3333:3306"
        volumes:
            - "./.docker/dbdata:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: gesttask
            MYSQL_ROOT_PASSWORD: root
networks:
    gesttaskapp:
        driver: bridge
